model:
  base: microsoft/phi-1_5
  lora_path: model_checkpoints/lora-song4jane

train:
  epochs: 3
  batch_size: 10

generate:
  max_new_tokens: 128
  temperature: 0.7

data:
  prompts: data/prompts.jsonl
  results_base: data/results_base.jsonl
  results_lora: data/results_lora.jsonl